let naam = "cornelia";
console.log(naam);
let som = 4 + 4;
console.log(som);
let optel = "4" + "4";
console.log(optel);
let plus = 3 + 2;
console.log(plus);
let min = 3 - 2;
console.log(min);
let keer = 3 * 2;
console.log(keer);
let delen = 4 / 2;
console.log(delen);
let perc = 100 % 2;
console.log(perc);
let age = 49;
console.log(typeof 49);
let woorden = "negenenveertig";
console.log(typeof woorden);